# Generated by Django 6.0.2 on 2026-03-31 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_is_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pds',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
