# Generated by Django 6.0.2 on 2026-05-22 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_auditlog_audit_audit_timesta_901180_idx'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditlog',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='auditlog',
            name='audit_audit_timesta_901180_idx',
        ),
    ]
