# Generated by Django 6.0.2 on 2026-03-23 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinformation',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
