# Generated by Django 6.0.2 on 2026-04-15 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_personalinformation_is_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentfolder',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
