# Generated by Django 6.0.2 on 2026-04-15 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_documentfolder_is_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentfolder',
            name='has_expiry',
            field=models.BooleanField(default=False),
        ),
    ]
