# Generated by Django 6.0.2 on 2026-05-22 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0004_documentfolder_has_expiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherdocument',
            name='restored_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
